version: '2'

services:
  mongo:
    build: ./compose/mongo
    ports:
        - "27017:27017"
    volumes:
      - ./data:/data

  processing:
    image: python:2.7
    build: 
      dockerfile: ./compose/processing/Dockerfile.dev
      context: .
    command: python /app/processor.py
    volumes:
      - ./processing:/app
    links: 
      - mongo
    depends_on:
      - mongo
   
  web:
    build: 
      dockerfile: ./compose/web/Dockerfile.dev
      context: .
    command: python /app/app.py
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    links:
      - mongo
    depends_on:
      - mongo
