version: '2'

volumes:
    mongo_data:
    mongo_backup:

services:
  mongo:
    build: ./compose/mongo
    ports:
        - "27017:27017"
    volumes:
      - mongo_data:/data

  processing:
    image: python:2.7
    build: 
      dockerfile: ./compose/processing/Dockerfile
      context: .
    command: python /app/processor.py
    links: 
      - mongo
    depends_on:
      - mongo
   
  web:
    build: 
      dockerfile: ./compose/web/Dockerfile
      context: .
    command: python /app/api.py
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - mongo

